name: Publish Docker image and update Kustomize

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and Update Kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo with Dockerfile
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rpchan44/webapp:v1.0-dev

      - name: Log Docker version
        run: docker --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            rpchan44/webapp:v1.0-dev
            rpchan44/webapp:v1.0-dev-${{ github.sha }}
            rpchan44/webapp:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check out the Kustomize repository
        uses: actions/checkout@v4
        with:
          repository: rpchan44/learn-kustomize
          token: ${{ secrets.GH_TOKEN }}
          path: ''
          show-progress: true

      - name: Update Kustomize manifest with new image
        run: |
          echo "Updating kustomization.yaml to use the latest image tag"
          IMAGE_TAG=${{ steps.meta.outputs.tags }}
          
          # Ensure the tag format is valid (e.g., avoid double colons or other issues)
          if [[ "$IMAGE_TAG" == *:*:* ]]; then
            IMAGE_TAG=$(echo "$IMAGE_TAG" | sed 's/:.*$//')  # Keep only the first part (repo:tag)
          fi

          sed -i "s|image: rpchan44/webapp:v1.0-dev:.*|image: rpchan44/webapp:v1.0-dev:$IMAGE_TAG|" overlays/dev/apps.yaml
          #echo "Debug Image : rpchan44/webapp:v1.0-dev:$IMAGE_TAG"
      - name: Commit changes to Kustomize repository
        run: |
          git config --global user.name "rpchan44"
          git config --global user.email "ronaldopchan@outlook.com"
          git add overlays/dev/apps.yaml
          git commit -m "Update Docker image tag in apps.yaml.yaml"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true
