jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and Update Kustomize
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository (the one with your Dockerfile)
      - name: Check out the main repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rpchan44/nodejs-app

      # Step 4: Log Docker version (optional but useful for debugging)
      - name: Log Docker version
        run: docker --version

      # Step 5: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            rpchan44/nodejs-app:latest
            rpchan44/nodejs-app:${{ github.sha }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Step 6: Check out the Kustomize repository into a directory
      - name: Check out the Kustomize repository
        uses: actions/checkout@v3
        with:
          repository: rpchan44/learn-kustomize  # Correct URL for the repository
          token: ${{ secrets.GH_TOKEN }}  # Use the correct GitHub token for access
          path: learn-kustomize  # This will check out the repo into the 'learn-kustomize' directory

      # Step 7: List the contents of the Kustomize repo for debugging
      - name: List contents of the Kustomize repository
        run: |
          echo "Listing contents of the Kustomize repository..."
          ls -R ./learn-kustomize

      # Step 8: Update kustomization.yaml with the new image tag
      - name: Update Kustomize manifest with the new image tag
        run: |
          echo "Updating kustomization.yaml to use the latest image tag"
          IMAGE_TAG=rpchan44/nodejs-app:main
          # Update the kustomization.yaml file located in learn-kustomize/overlays/dev
          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" ./learn-kustomize/overlays/dev/kustomization.yaml

      # Step 9: Commit changes to the Kustomize repository
      - name: Commit changes to Kustomize repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./learn-kustomize/overlays/dev/kustomization.yaml
          git commit -m "Update Docker image tag in kustomization.yaml"
          git push origin main  # Make sure this matches the branch you're using
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
