name: Publish Docker image and update k8s manifest

on:
  push:
    branches: 
      - main
      - development

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and Update Kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo with Dockerfile
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rpchan44/webapp-dev

      - name: Log Docker version
        run: docker --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build Docker image
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker build -t rpchan44/webapp-prod:${{ github.sha }} .
          else
            docker build -t rpchan44/webapp-dev:${{ github.sha }} .
          fi
      
      - name: Push Docker image to DockerHub
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker push rpchan44/webapp-prod:${{ github.sha }}
          else
            docker push rpchan44/webapp-dev:${{ github.sha }}
          fi

      - name: Check out the Kustomize repository
        uses: actions/checkout@v4
        with:
          repository: rpchan44/k8s-control
          token: ${{ secrets.GH_TOKEN }}
          path: ''
          show-progress: true
      
      - name: Update Kustomize manifest with new image
        run: |
          echo "Updating kustomization.yaml to use the latest image tag"
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            sed -i "s/webapp-prod:.*/webapp-prod:${{ github.sha }}/g" overlays/prod/apps.yaml
          else
            sed -i "s/webapp-dev:.*/webapp-dev:${{ github.sha }}/g" overlays/dev/apps.yaml
          fi
          
      - name: Commit changes to Kustomize repository
        run: |
          git config --global user.name "rpchan44"
          git config --global user.email "ronaldopchan@outlook.com"
          git diff --exit-code overlays/dev/apps.yaml || {
            git add overlays/dev/apps.yaml
            git commit -m "Release webapp-${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}:${{ github.sha }}"
            git push origin main
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: false
