name: Publish Docker image and update k8s manifest

on:
  pull_request:
    paths:
      - '**/*.py'  # Run on any Python file change
  push:
    branches: 
      - rolling-update

jobs:
   push_to_registry:
    name: Push Docker image to Docker Hub and Update Kustomize
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo with Dockerfile
        uses: actions/checkout@v4
        with:
          ref: rolling-update
          repository: rpchan44/learn-github-action
          token: ${{ secrets.GH_TOKEN }}
          path: ''
          show-progress: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Choose your preferred Python version

      - name: Read current version
        id: read_version
        run: |
          version=$(cat version.txt)
          echo "Current version: $version"
          echo "current_version=$version" >> $GITHUB_ENV  # Set current_version using GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ env.current_version }}
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "$new_version" > version.txt
          echo "new_version=$new_version" >> $GITHUB_ENV  # Set new version in GITHUB_ENV
      
      - name: Set up Git
        run: |
          git config --global user.name "rpchan44"
          git config --global user.email "ronaldopchan@outlook.com"
      
      - name: Commit version.txt and push
        run: |
          git add version.txt
          git commit -m "Update version to ${{ env.new_version }}"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Prevent workflow trigger from itself
        if: github.actor != 'github-actions[bot]'
        run: echo "This commit won't trigger the workflow"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff  # Install Ruff

      - name: Performing code linting && formatting
        run: |
          ruff check .  
          ruff format . 

      - name: Commit and push changes (if any)
        if: success() && steps.format.outputs.changed == 'true'
        run: |
          git config --global user.name "rpchan44"
          git config --global user.email "ronaldopchan@outlook.com"
          git add .
          git commit -m "Apply code formatting"
          git push ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rpchan44/webapp-dev

      - name: Log Docker version
        run: docker --version

      - name: Build Docker image
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker build --build-arg ENVIRONMENT=production -t rpchan44/webapp-prod:${{ github.sha }} .
            docker build --build-arg ENVIRONMENT=production -t rpchan44/webapp-prod-canary:${{ github.sha }} .
          else
            docker build --build-arg ENVIRONMENT=development -t rpchan44/webapp-dev:${{ github.sha }} .
            docker build --build-arg ENVIRONMENT=development -t rpchan44/webapp-dev-canary:${{ github.sha }} .
          fi
          echo "Building project with version ${{ steps.increment.outputs.new_version }}"
      
      - name: Push Docker image to DockerHub
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            docker push rpchan44/webapp-prod:${{ github.sha }}
            docker push rpchan44/webapp-prod-canary:${{ github.sha }}
          else
            docker push rpchan44/webapp-dev:${{ github.sha }}
            docker push rpchan44/webapp-dev-canary:${{ github.sha }}
          fi

      - name: Check out the Kustomize repository
        uses: actions/checkout@v4
        with:
          ref: feature/canary-argo
          repository: rpchan44/k8s-control
          token: ${{ secrets.GH_TOKEN }}
          path: ''
          show-progress: true
      
      - name: Update Kustomize manifest with new image
        run: |
          echo "Updating kustomization.yaml to use the latest image tag"
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            sed -i "s/webapp-prod:.*/webapp-prod:${{ github.sha }}/g" overlays/prod/apps.yaml
          else
            sed -i "s/webapp-dev:.*/webapp-dev:${{ github.sha }}/g" overlays/dev/apps.yaml
          fi
          
      - name: Commit changes to Kustomize repository
        run: |
          git config --global user.name "rpchan44"
          git config --global user.email "ronaldopchan@outlook.com"
          git diff --exit-code overlays/${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}/apps.yaml || {
          git add overlays/${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}/apps.yaml
          git commit -m "Release webapp-${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}:${{ github.sha }}"
          git push origin feature/canary-argo
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          continue-on-error: false
